# Generated by Django 4.1.10 on 2023-07-23 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_chapter', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_poster', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
            ],
            options={
                'db_table': 'createChapter',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key_details', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'opportunity',
            },
        ),
    ]
