# Generated by Django 4.1.10 on 2023-07-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opportunity',
            table=None,
        ),
    ]
