# Generated by Django 4.1.10 on 2023-07-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechConnect', '0002_alter_opportunity_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opportunity',
            table='opportunity',
        ),
    ]
